### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by elsteelbrain**

### CODE REVIEW

**Comment by mthenw** [comment]
@elsteelbrain any idea why TravisCI is not running?

**Comment by p0wl** [comment]
why did you delete the "configure" function? The commit message "fix tests" does not really help...

**Comment by elsteelbrain** [comment]
I should've been more explicit in the messages but we decided to remove the `configure` method in another conversation.

**Comment by p0wl** [comment]
is that conversation public? I'm asking because I'm thinking if it is worth porting https://github.com/serverless/fdk/pull/81 to event-gateway-sdk, but if you don't see value in such a functionality (as it is similar to configure), I won't do it.

**Comment by elsteelbrain** [comment]
The decision was made in a private conversation. @mthenw what is your opinion on this?

**Comment by mthenw** [comment]
Hi @p0wl thanks for asking!

In general, because of how Event Gateway works right now there is no way to provide atomic operation allowing configuring multiple functions/subscriptions. That's why in some cases that would cause an inconsistent state in the EG comparing to what user defined. That's why we decided to fix it in the EG in the first place and then add `configure` method in SDK.

In general, the plan is allowing configuring whole space in one atomic operation in EG.

Let me know if you have more questions.

**Pull request merged**
